modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional Creditos a alguien?
authors="${mod_authors}" #optional
displayTest="MATCH_VERSION" # Checkea misma version en cliente y servidor
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    #Versiones desde la 4.4 hasta la 4.5 exclusive
    versionRange="[4.4,4.5)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    mandatory=true
    #Versiones desde la 3.0.1.4 en adelante
    versionRange="${terrablender_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"