blank_issues_enabled: false
contact_links:
  - name: Discord DMZ Server
    url: https://discord.gg/b5MgRNb3D7
    about: If you believe your issue can be resolved/implemented quickly, please join our Discord server.