blank_issues_enabled: false
contact_links:
  - name: Discord DMZ Server
    url: https://discord.gg/b5MgRNb3D7
    about: Please ask and answer questions here, you can make suggestions and check the changelog, too.
  - name: Follow CurseForge DMZ Updates
    url: https://www.curseforge.com/minecraft/mc-mods/dragonminez
    about: Stay up to date with the latest releases.
