name: Auto-Bump Mod Version

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-bump:
    if: contains(github.event.label.name, 'major') || contains(github.event.label.name, 'minor') || contains(github.event.label.name, 'patch')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump mod_version
        run: |
          # Read the current mod_version
          current_version=$(grep -E '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "Current mod_version: $current_version"

          # Extract major, minor, patch
          major=$(echo "$current_version" | cut -d'.' -f1)
          minor=$(echo "$current_version" | cut -d'.' -f2)
          patch=$(echo "$current_version" | cut -d'.' -f3)

          # Determine the bump type based on the label
          case "${{ github.event.label.name }}" in
            major) major=$((major + 1)); minor=0; patch=0;;
            minor) minor=$((minor + 1)); patch=0;;
            patch) patch=$((patch + 1));;
          esac

          # Construct the new version
          new_version="$major.$minor.$patch"
          echo "New mod_version: $new_version"

          # Update gradle.properties
          sed -i "s/^mod_version=.*/mod_version=$new_version/" gradle.properties

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties
          git commit -m "Auto-bumped mod_version to $new_version"
          git push origin ${{ github.head_ref }}
