name: "TODO Workflow"
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Run todo-to-issue-action"
        uses: "alstr/todo-to-issue-action@v4"
        with:
          CLOSE_ISSUES: true
          AUTO_P: true
