name: "TO-DO Workflow"
on:
  push:
    branches-ignore:
      - main
    paths:
      - src/main/java/com/yuseix/dragonminez/**

jobs:
  todo-to-issue:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Run todo-to-issue Action"
        uses: "alstr/todo-to-issue-action@v5.1.3"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_ISSUES: true
          AUTO_P: true
